# -*- coding: utf-8 -*-
"""Python-Codes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MBwTcE1jKzxEQuf3aCCLkjgLPMEuCey8
"""

number = 35000
sentence1 = "Mojo is {} times faster than Python"
sentence2 = "Mojo is {:,} times faster than Python"

print (sentence1.format(number))
print (sentence2.format(number))

import matplotlib.pyplot as plt

hour_minute = {}
minute_hour = {}

for i in range(0,13):

  if (i < 10):
      i = "0" + str(i)
  else:
    i = "" + str(i)

  for j in range(0,13):

    if (j < 10):
      j = "0" + str(j)
    else:
      j = "" + str(j)

    if (int(j) != 0):
      hour_minute[i + ":" + j] = int(i) / int(j)
    else:
      hour_minute[i + ":" + j] = 10

    if (int(i) != 0):
      minute_hour[i + ":" + j] = int(j) / int(i)
    else:
      minute_hour[i + ":" + j] = 10

plt.plot(hour_minute.keys(), hour_minute.values())

plt.plot(minute_hour.keys(), minute_hour.values())